### ISSUE TITLE
（采）采购单

### ISSUE THREAD

**Issue by mitoriko** [A-Cubic/CBEC-B2B-WEB#16]
界面一：采购单列表
路由：/trade/order-p/list
界面样式：列表页
描述：获取该采购商所有未完成采购单，筛选条件是时间、单号、状态
链接：新增、修改（未处理）、提交（保存未提交）、撤回（未处理）、查看、处理

界面二：新增
路由：/trade/order-p/add
界面样式：分步表单，主表单分表头、商品列表、运费信息、合计信息
描述：
step 1：
采购单主表单页面，表单头包含：新增商品、保存、放弃按钮；
商品列表区域显示选择商品列表，列表显示商品信息、单价、数量（可修改）、合计；
运费显示“待报价”
总价显示商品合计与运费总价格；
点击新增商品弹窗显示step 2
step 2：
商品列表，头部显示按钮，首次加载显示热门推荐商品，可通过品名、条码搜索，多选（最好），点击确认，弹窗消失，主表单增加相应商品信息；
链接：放弃、保存（仅保存采购单，状态为未发起询价）、提交（保存并修改状态进入询价流程）

界面三：修改
路由：/trade/order-p/mod/:id
界面样式：参照新增
描述：参照新增
链接：保存

~~界面四：查看~~
~~路由：/trade/order-p/info/:id~~
~~界面样式：参照修改~~
~~描述：参照修改，数据不可修改，不需要step 2弹窗功能~~
~~链接：关闭~~

界面四：处理
路由：/trade/order-p/handle/:id
界面样式：参照查看
描述：参照查看，数据不可修改，不需要step 2弹窗功能，增加remark区域（留言板类似）
链接：确认、调整（弹窗填写备注信息，并提交）

**Comment by h123a** [comment]
/llback/purchase/list 采购单列表

![1519541828 1](https://user-images.githubusercontent.com/35676474/36638952-2d18a78c-1a3c-11e8-90b4-937d199a5fd1.png)
查询参数
userCode;//采购商账号 管理员置空
purchasesn;//采购单号 
createtime;//建立时间 20180225
stage;//采购单阶段 
*采购单阶段：0：暂存，1：询价，2：待付款，3：备货中，4：已出港，5：已入港，9：完成

**Comment by h123a** [comment]
/llback/purchase/goods  获取采购单商品列表



查询字段
userCode;//采购单对应的采购商账号  
purchasesn;//采购单号

返回
id;   //主键
purchasesn;   //采购单号
goodsid;   //商品ID
goodsname;   //商品名称
price;   //商品价格
deliverytype;   //提货方式
expectprice;   //期望价格
realprice;   //实际价格
total;   //商品数量
barcode;   //产品条码
costprice;   //成本价
otherprice;   //其他费用
supplierid;   //供货商ID

**Comment by h123a** [comment]
/llback/purchase/goods  获取采购单商品列表



查询字段
userCode;//采购单对应的采购商账号  
purchasesn;//采购单号

返回
id;   //主键
purchasesn;   //采购单号
goodsid;   //商品ID
goodsname;   //商品名称
price;   //商品价格
deliverytype;   //提货方式
expectprice;   //期望价格
realprice;   //实际价格
total;   //商品数量
barcode;   //产品条码
costprice;   //成本价
otherprice;   //其他费用
supplierid;   //供货商ID

**Comment by h123a** [comment]
/llback/purchase/add 生成采购单

![1519550373 1](https://user-images.githubusercontent.com/35676474/36639859-118351ca-1a50-11e8-9376-9d2304439328.png)
参数说明：
stege:一般默认给“0”（暂存）即可，如果是直接确认询价就赋值“1”（询价）。
status：默认给“1”（刚录入等待处理）。
sendtype：给t_base_sendtyp的id。（见/llback/goods/sendtype获取发货方式接口）
返回参数：
现在返回的是影响条数，看需要什么返回值，我再调整。

**Comment by h123a** [comment]
/llback/goods/sendtype  获取发货方式

![1519551791 1](https://user-images.githubusercontent.com/35676474/36640053-6042e7fa-1a53-11e8-83d2-8247ec86e607.png)

**Comment by h123a** [comment]
/llback/purchase/update 修改采购单

![1519553396 1](https://user-images.githubusercontent.com/35676474/36640323-1beba57a-1a57-11e8-9f43-983e9d8dfa47.png)

其中purchasesn是必须有的，其他的字段可以根据业务决定。
现在返回的是影响条数，看需要什么返回值，我再调整。

**Comment by mitoriko** [comment]
归口**查看**功能到**处理**

**Comment by pangbooo** [comment]
采购单列表接口需要分页参数 @h123a

**Comment by h123a** [comment]
/llback/purchase/goods/add 新增采购单商品
图片上传不上去
传递的参数
{
        "purchasesn": "123",
        "goodsid": "1",
        "goodsname": "测试商品",
        "price": "100",
        "deliverytype": "1",
        "expectprice": "2000",
        "barcode": "123445677",
        "total": "50"
}
返回参数：正确，返回1，错误返回错误信息

**Comment by h123a** [comment]
/llback/purchase/goods/update 修改采购单商品

**Comment by h123a** [comment]
/llback/purchase/goods/del 删除采购单商品

![1519871884 1](https://user-images.githubusercontent.com/35676474/36824317-a4bc2112-1d3c-11e8-9750-7830938ec831.png)

**Comment by h123a** [comment]
/llback/purchase/split 采购单提交并分拆询价单
![1520240883 1](https://user-images.githubusercontent.com/35676474/36966436-c4c0ab6e-2097-11e8-8ce7-2749b94dc2e3.jpg)

提交成功后会把stage变1，t_purchase_inquiry表中添加新的数据。
错误会返回错误信息
